import { SVGProps } from "react";

export type IconSvgProps = SVGProps<SVGSVGElement> & {
  size?: number;
};

// Conversation starter structure
export interface ConversationStarter {
  title: string;
  question: string;
  openingRemarks?: string; // Optional pre-written response to avoid AI latency on first interaction
}

// Voice emotion options for avatar speech
export enum VoiceEmotion {
  EXCITED = "excited",
  SERIOUS = "serious",
  FRIENDLY = "friendly",
  SOOTHING = "soothing",
  BROADCASTER = "broadcaster"
}

// Avatar voice configuration
export interface VoiceConfig {
  rate: number; // 0.5 - 2.0
  voiceId: string;
  emotion?: VoiceEmotion;
}

// Avatar rendering and behavior settings
export interface StartAvatarRequest {
  quality: "low" | "medium" | "high";
  avatarName: string;
  knowledgeId?: string;
  voice: VoiceConfig;
  language: string; // Two lowercase letters (en, zh, ko, vi, fr, de, ja)
}

/**
 * CHAT STORAGE IMPLEMENTATION - CENTRALIZED TYPE DEFINITIONS
 * 
 * This section implements the chat storage types required by the meeting summary (Section #9).
 * The meeting specified: "serialize the chat as one JSON file in S3 under a future /chats/ prefix"
 * and "maybe store chat-IDs in IndexedDB for quick lookup".
 * 
 * These types provide the foundation for the entire chat storage system and ensure
 * consistency across all components, services, and API endpoints.
 */

/**
 * ChatMessage Interface
 * 
 * Centralizes the chat message structure that was previously duplicated across components.
 * This replaces the local ChatMessage interfaces in:
 * - app/kiosk/touch-screen/page.tsx
 * - app/kiosk/main-display/page.tsx
 * - components/preview-chat-full.tsx
 * - components/preview-chat-small.tsx
 * 
 * Design decisions:
 * - Uses "user" | "assistant" roles to match OpenAI API conventions
 * - Timestamp as number (Unix timestamp) for easy sorting and date operations
 * - Content as string to support both text and special status messages ("🎤 Recording...")
 * - Minimal structure for efficient storage and transmission
 */
export interface ChatMessage {
  role: "user" | "assistant";           // Message sender - user input or AI response
  content: string;                       // Message text content
  timestamp: number;                     // Unix timestamp when message was created
}

/**
 * ChatSessionMetadata Interface
 * 
 * Contains all metadata about a chat session for analytics, filtering, and management.
 * This supports the "analytics pipeline" mentioned as future work in the meeting.
 * 
 * Key features:
 * - sessionId: Unique identifier for the chat session (timestamp + random)
 * - avatarId/avatarName: Links chat to specific avatar for analytics
 * - userId/userName: Optional user identification (for future user tracking)
 * - startTime/endTime: Session duration tracking
 * - messageCount: Quick metric without loading full messages array
 * - isKioskMode: Distinguishes kiosk interactions from preview chats
 * - location: Future support for multiple kiosk locations
 */
export interface ChatSessionMetadata {
  sessionId: string;                     // Unique session identifier (generated by S3 client)
  avatarId: string;                      // ID of avatar involved in conversation
  avatarName: string;                    // Name of avatar (for display/analytics)
  userId?: string;                       // Optional user identifier (future enhancement)
  userName?: string;                     // Optional user name (future enhancement)
  startTime: number;                     // Unix timestamp when chat session began
  endTime: number;                       // Unix timestamp when chat session ended
  messageCount: number;                  // Total number of messages in session
  isKioskMode: boolean;                  // True for kiosk interactions, false for preview chats
  location?: string;                     // Optional kiosk location identifier (future use)
}

/**
 * ChatSession Interface
 * 
 * Complete chat session structure for S3 storage, implementing the meeting requirement:
 * "serialize the chat as one JSON file in S3 under a future /chats/ prefix"
 * 
 * This is the main data structure that gets saved to S3 as JSON files.
 * Structure: chats/{sessionId}.json
 * 
 * Design rationale:
 * - metadata: Separate object for easy querying and analytics
 * - messages: Array of all chat messages in chronological order
 * - createdAt/updatedAt: Standard audit fields for debugging and sync
 * 
 * Example S3 storage:
 * chats/1703123456789_abc123def.json = {
 *   metadata: { sessionId: "1703123456789_abc123def", avatarId: "weather-bot", ... },
 *   messages: [{ role: "user", content: "Hello", timestamp: 1703123456789 }, ...],
 *   createdAt: "2023-12-20T12:34:56.789Z",
 *   updatedAt: "2023-12-20T12:34:56.789Z"
 * }
 */
export interface ChatSession {
  metadata: ChatSessionMetadata;         // Session metadata for analytics and filtering
  messages: ChatMessage[];              // Complete conversation history
  createdAt: string;                     // ISO timestamp when session was first created
  updatedAt: string;                     // ISO timestamp when session was last modified
}

/**
 * ==================================================================================
 * CALL TO ACTION (CTA) TYPES - NEW IMPLEMENTATION
 * ==================================================================================
 * 
 * Types for the Call to Action feature that allows users to save chat sessions
 * and connect with Weatherhead via QR codes and forms.
 */

/**
 * CTA Configuration Interface
 * 
 * Stores admin-configurable settings for the CTA system.
 * This is stored in S3 and managed through the admin portal.
 */
export interface CTAConfig {
  id: string;                           // Configuration ID (default: "main")
  enabled: boolean;                     // Whether CTA feature is active
  emailRecipients: string[];            // Case email addresses to notify on submissions
  qrCodeBaseUrl: string;                // Base URL for QR code links (e.g., "https://domain.com/cta")
  formTitle: string;                    // Title displayed on the CTA form
  formDescription: string;              // Description text on the CTA form
  submitButtonText: string;             // Text for the submit button
  successMessage: string;               // Message shown after successful submission
  emailSubject: string;                 // Email subject template
  emailTemplate: string;                // Email body template (with placeholders)
  maxMessageLength: number;             // Maximum characters for user message (default: 500)
  lastUpdated: string;                  // ISO timestamp of last configuration update
  updatedBy: string;                    // User who last updated the configuration
}

/**
 * CTA Form Submission Interface
 * 
 * Data structure for user form submissions.
 * Stored in S3 for admin portal viewing and analytics.
 */
export interface CTASubmission {
  submissionId: string;                 // Unique submission identifier
  sessionId: string;                    // Associated chat session ID
  userDetails: {
    name: string;                       // User's name
    email: string;                      // User's email address
    message: string;                    // User's message (max 500 chars)
  };
  metadata: {
    submittedAt: string;                // ISO timestamp of submission
    ipAddress?: string;                 // User's IP address (optional, for analytics)
    userAgent?: string;                 // User's browser info (optional, for analytics)
    avatarId: string;                   // Avatar ID from the chat session
    avatarName: string;                 // Avatar name from the chat session
    messageCount: number;               // Number of messages in the chat session
    chatDuration: number;               // Duration of chat in milliseconds
  };
  status: "pending" | "processed" | "failed";  // Processing status
  emailSent: boolean;                   // Whether notification emails were sent
  createdAt: string;                    // ISO timestamp when submission was created
  processedAt?: string;                 // ISO timestamp when submission was processed
  errorMessage?: string;                // Error details if processing failed
}

/**
 * QR Code Data Interface
 * 
 * Structure of data encoded in QR codes displayed on kiosk.
 * This data is URL-encoded and embedded in the QR code.
 */
export interface QRCodeData {
  sessionId: string;                    // Current chat session ID
  avatarId: string;                     // Current avatar ID
  avatarName: string;                   // Current avatar name
  timestamp: number;                    // When QR code was generated
  version: string;                      // QR code format version (for future compatibility)
}

/**
 * CTA Form Data Interface
 * 
 * Structure for form data submitted by users.
 * Used for validation and processing.
 */
export interface CTAFormData {
  sessionId: string;                    // Chat session ID from QR code
  name: string;                         // User's name (required)
  email: string;                        // User's email (required, validated)
  message: string;                      // User's message (optional, max 500 chars)
  qrCodeData?: {                        // QR code validation data (optional, for enhanced validation)
    avatarId: string;
    avatarName: string;
    timestamp: number;
    version: string;
  };
}

/**
 * Email Template Variables Interface
 * 
 * Variables available for email template substitution.
 * Allows dynamic content in notification emails.
 */
export interface EmailTemplateVars {
  userName: string;                     // User's submitted name
  userEmail: string;                    // User's submitted email
  userMessage: string;                  // User's submitted message
  avatarName: string;                   // Avatar name from chat session
  submissionDate: string;               // Formatted submission date
  sessionId: string;                    // Chat session ID
  messageCount: number;                 // Number of messages in chat
  chatDuration: string;                 // Formatted chat duration
}

/**
 * ==================================================================================
 * CASE AUTHORING SYSTEM - PROFESSOR PORTAL TYPES
 * ==================================================================================
 * 
 * Types for the case authoring system that allows professors to create
 * structured learning scenarios with visual scenario builders.
 */

/**
 * Course Interface
 * 
 * Represents a course that contains multiple cases.
 * Courses are the top-level organizational unit for professors.
 */
export interface Course {
  id: string;                           // Unique course identifier
  name: string;                         // Course name (e.g., "Business Ethics 101")
  code: string;                         // Course code (e.g., "MGMT 301")
  description?: string;                 // Course description
  semester: string;                     // Semester (e.g., "Spring 2026")
  professorId: string;                  // ID of the professor who owns this course
  professorName: string;                // Name of the professor
  createdAt: string;                    // ISO timestamp when course was created
  updatedAt: string;                    // ISO timestamp when course was last modified
}

/**
 * Learning Objective Interface
 * 
 * Defines what students should learn from a case.
 * Used for scoring and analytics.
 */
export interface LearningObjective {
  id: string;                           // Unique objective identifier
  title: string;                        // Short title (e.g., "Identify symptoms")
  description: string;                  // Detailed description
  type: "knowledge" | "skill" | "attitude";  // Bloom's taxonomy category
  weight: number;                       // Scoring weight (1-10)
}

/**
 * Scenario Node Types
 * 
 * Different types of nodes in the visual scenario builder.
 */
export type ScenarioNodeType = 
  | "opening"      // Avatar's first message
  | "dialogue"     // Avatar speaks
  | "question"     // Avatar asks student something
  | "listen"       // Wait for student response
  | "branch"       // Route based on response
  | "feedback"     // Provide guidance
  | "checkpoint"   // Score a learning objective
  | "ending";      // Conclude scenario

/**
 * Branch Condition Interface
 * 
 * Defines conditions for branching logic.
 */
export interface BranchCondition {
  id: string;                           // Unique condition identifier
  type: "keyword" | "intent" | "sentiment" | "default";
  value?: string;                       // Keyword or intent to match
  targetNodeId: string;                 // Node to go to if condition matches
}

/**
 * Scenario Node Interface
 * 
 * Represents a single node in the scenario flow.
 */
export interface ScenarioNode {
  id: string;                           // Unique node identifier
  type: ScenarioNodeType;               // Type of node
  label: string;                        // Display label in builder
  content: string;                      // Main content (dialogue text, question, etc.)
  
  // Position in visual builder
  position: {
    x: number;
    y: number;
  };
  
  // Node-specific configuration
  config: {
    // For "listen" nodes
    timeout?: number;                   // Seconds to wait before fallback
    fallbackMessage?: string;           // Message if timeout
    
    // For "branch" nodes
    conditions?: BranchCondition[];     // Branching conditions
    
    // For "checkpoint" nodes
    objectiveId?: string;               // Learning objective to score
    scoringCriteria?: string;           // How to evaluate
    
    // For "feedback" nodes
    feedbackType?: "positive" | "negative" | "neutral";
    
    // For "question" nodes
    expectedPatterns?: string[];        // Expected answer patterns
    hints?: string[];                   // Hints to provide
  };
  
  // Connections to other nodes
  nextNodeId?: string;                  // Default next node (for linear flow)
}

/**
 * Scenario Edge Interface
 * 
 * Represents a connection between two nodes in the visual builder.
 */
export interface ScenarioEdge {
  id: string;                           // Unique edge identifier
  sourceNodeId: string;                 // Starting node
  targetNodeId: string;                 // Ending node
  label?: string;                       // Optional label for the edge
  conditionId?: string;                 // For branch nodes, which condition this edge represents
}

/**
 * Avatar Persona Configuration
 * 
 * Case-specific avatar personality settings.
 */
export interface AvatarPersonaConfig {
  baseAvatarId: string;                 // Reference to base avatar
  caseContext: string;                  // Case-specific context to inject
  personalityTraits: {
    formality: number;                  // 1-10: Casual to Formal
    patience: number;                   // 1-10: Quick to Patient
    empathy: number;                    // 1-10: Neutral to Empathetic
    directness: number;                 // 1-10: Indirect to Direct
  };
  knowledgeBoundaries: {
    canDiscuss: string[];               // Topics the avatar can discuss
    cannotDiscuss: string[];            // Topics to avoid
  };
}

/**
 * Guardrails Configuration for Case
 * 
 * Safety and content filtering settings.
 */
export interface CaseGuardrails {
  blockedTopics: string[];              // Topics to block
  offTopicResponse: string;             // Response when off-topic
  maxResponseLength: number;            // Maximum response length
  requireFactCheck: boolean;            // Whether to fact-check responses
}

/**
 * Case Interface
 * 
 * Main case/scenario entity that professors create.
 * Contains all configuration for a learning scenario.
 */
export interface Case {
  id: string;                           // Unique case identifier
  courseId: string;                     // Parent course ID
  name: string;                         // Case name
  description: string;                  // Case description
  
  // Case metadata
  difficulty: "beginner" | "intermediate" | "advanced";
  estimatedDuration: number;            // Minutes
  status: "draft" | "published" | "archived";
  
  // Learning objectives
  learningObjectives: LearningObjective[];
  
  // Scenario structure
  nodes: ScenarioNode[];                // All nodes in the scenario
  edges: ScenarioEdge[];                // Connections between nodes
  startNodeId: string;                  // ID of the starting node
  
  // Avatar configuration
  avatarConfig: AvatarPersonaConfig;
  
  // Safety settings
  guardrails: CaseGuardrails;
  
  // Audit fields
  createdBy: string;                    // Professor ID
  createdByName: string;                // Professor name
  lastEditedBy: string;                 // Last editor ID
  lastEditedByName: string;             // Last editor name
  createdAt: string;                    // ISO timestamp
  updatedAt: string;                    // ISO timestamp
  publishedAt?: string;                 // ISO timestamp when published
}

/**
 * Case Session Interface
 * 
 * Runtime session when a student interacts with a case.
 * Extends the base ChatSession with case-specific data.
 */
export interface CaseSession {
  id: string;                           // Session ID
  caseId: string;                       // Case being run
  courseId: string;                     // Parent course
  
  // Current state
  currentNodeId: string;                // Current position in scenario
  visitedNodeIds: string[];             // Nodes visited so far
  
  // Scoring
  objectiveScores: Record<string, number>;  // Scores per objective
  totalScore: number;                   // Overall score
  
  // Session metadata
  studentId?: string;                   // Optional student identifier
  kioskId?: string;                     // Kiosk identifier
  startTime: number;                    // Unix timestamp
  endTime?: number;                     // Unix timestamp when completed
  completionStatus: "in_progress" | "completed" | "abandoned";
  
  // Chat history (extends ChatMessage with node tracking)
  messages: Array<ChatMessage & {
    nodeId?: string;                    // Which node triggered this message
    scoreDelta?: number;                // Score change from this message
  }>;
  
  createdAt: string;
  updatedAt: string;
}

/**
 * Case Analytics Summary
 * 
 * Aggregated analytics for a case.
 */
export interface CaseAnalytics {
  caseId: string;
  totalSessions: number;
  completedSessions: number;
  averageScore: number;
  averageDuration: number;              // Minutes
  objectiveSuccessRates: Record<string, number>;  // Percentage per objective
  commonMistakes: Array<{
    nodeId: string;
    description: string;
    frequency: number;
  }>;
  lastUpdated: string;
}
